--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 31/03/2021 21:26:17
-- Server version: 5.5.5-10.4.18-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE sis_invcon;

--
-- Drop table `vacios_flota`
--
DROP TABLE IF EXISTS vacios_flota;

--
-- Drop table `usuario_permiso`
--
DROP TABLE IF EXISTS usuario_permiso;

--
-- Drop table `permiso`
--
DROP TABLE IF EXISTS permiso;

--
-- Drop procedure `actualizar_ingreso`
--
DROP PROCEDURE IF EXISTS actualizar_ingreso;

--
-- Drop procedure `datosingreso`
--
DROP PROCEDURE IF EXISTS datosingreso;

--
-- Drop procedure `listardatosm`
--
DROP PROCEDURE IF EXISTS listardatosm;

--
-- Drop table `posicion`
--
DROP TABLE IF EXISTS posicion;

--
-- Drop table `bloque`
--
DROP TABLE IF EXISTS bloque;

--
-- Drop table `asignaciones`
--
DROP TABLE IF EXISTS asignaciones;

--
-- Drop table `conexion`
--
DROP TABLE IF EXISTS conexion;

--
-- Drop table `desconexion`
--
DROP TABLE IF EXISTS desconexion;

--
-- Drop table `envios`
--
DROP TABLE IF EXISTS envios;

--
-- Drop table `exportacion`
--
DROP TABLE IF EXISTS exportacion;

--
-- Drop procedure `insertar_monitoreo`
--
DROP PROCEDURE IF EXISTS insertar_monitoreo;

--
-- Drop procedure `listar_Monitoreo`
--
DROP PROCEDURE IF EXISTS listar_Monitoreo;

--
-- Drop table `monitoreo`
--
DROP TABLE IF EXISTS monitoreo;

--
-- Drop table `ingreso_maestro`
--
DROP TABLE IF EXISTS ingreso_maestro;

--
-- Drop table `vacios_despachos`
--
DROP TABLE IF EXISTS vacios_despachos;

--
-- Drop table `flota_transporte`
--
DROP TABLE IF EXISTS flota_transporte;

--
-- Drop table `movimientos`
--
DROP TABLE IF EXISTS movimientos;

--
-- Drop table `vacios_ingresos`
--
DROP TABLE IF EXISTS vacios_ingresos;

--
-- Drop table `usuarios`
--
DROP TABLE IF EXISTS usuarios;

--
-- Drop table `rol`
--
DROP TABLE IF EXISTS rol;

--
-- Set default database
--
USE sis_invcon;

--
-- Create table `rol`
--
CREATE TABLE rol (
  id_rol INT(11) NOT NULL AUTO_INCREMENT,
  descripcion CHAR(20) DEFAULT NULL,
  PRIMARY KEY (id_rol)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `usuarios`
--
CREATE TABLE usuarios (
  id_usuario INT(11) NOT NULL AUTO_INCREMENT,
  nombre_usuario CHAR(20) DEFAULT NULL,
  usuario CHAR(20) DEFAULT NULL,
  clave VARCHAR(250) DEFAULT NULL,
  condicion INT(11) DEFAULT NULL,
  id_rol INT(11) DEFAULT NULL,
  imagen VARCHAR(50) DEFAULT NULL,
  email VARCHAR(75) DEFAULT NULL,
  departamento VARCHAR(50) DEFAULT NULL,
  empresa VARCHAR(75) DEFAULT NULL,
  PRIMARY KEY (id_usuario)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE usuarios 
  ADD CONSTRAINT usuario_rol FOREIGN KEY (id_rol)
    REFERENCES rol(id_rol);

--
-- Create table `vacios_ingresos`
--
CREATE TABLE vacios_ingresos (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Fecha_Ingreso DATE DEFAULT NULL,
  Hora_De_Ingreso DATETIME DEFAULT NULL,
  SZ CHAR(20) DEFAULT NULL,
  Dry_Reefer CHAR(20) DEFAULT NULL,
  Clasificacion CHAR(20) DEFAULT NULL,
  Contenido CHAR(20) DEFAULT NULL,
  Procedencia CHAR(20) DEFAULT NULL,
  TIR CHAR(20) DEFAULT NULL,
  HR_TIR CHAR(20) DEFAULT NULL,
  Transporte CHAR(20) DEFAULT NULL,
  Ubicacion CHAR(20) DEFAULT NULL,
  Estatus CHAR(20) DEFAULT NULL,
  Predio_From CHAR(20) DEFAULT NULL,
  Fecha DATE DEFAULT NULL,
  Sello_Export CHAR(20) DEFAULT NULL,
  Sello_Alopsa CHAR(20) DEFAULT NULL,
  Buque CHAR(20) DEFAULT NULL,
  ETA CHAR(20) DEFAULT NULL,
  Booking CHAR(20) DEFAULT NULL,
  Cliente CHAR(20) DEFAULT NULL,
  Producto CHAR(20) DEFAULT NULL,
  No_De_ATC CHAR(20) DEFAULT NULL,
  Peso_Tara CHAR(20) DEFAULT NULL,
  Fecha_Emision CHAR(20) DEFAULT NULL,
  Fecha_Vencimiento CHAR(20) DEFAULT NULL,
  Fecha_Actual CHAR(20) DEFAULT NULL,
  Dias_Estadia CHAR(20) DEFAULT NULL,
  Problemas_ATC CHAR(20) DEFAULT NULL,
  Forecast CHAR(20) DEFAULT NULL,
  Chatarra CHAR(20) DEFAULT NULL,
  Daños CHAR(20) DEFAULT NULL,
  Año_De_Fabricacion DATE DEFAULT NULL,
  id_usuario INT(11) NOT NULL,
  PRIMARY KEY (Id, id_usuario)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE vacios_ingresos 
  ADD CONSTRAINT usuario_vacio_ingreso FOREIGN KEY (id_usuario)
    REFERENCES usuarios(id_usuario);

--
-- Create table `movimientos`
--
CREATE TABLE movimientos (
  Id_Movimientos INT(11) NOT NULL AUTO_INCREMENT,
  Semana CHAR(20) DEFAULT NULL,
  Año CHAR(20) DEFAULT NULL,
  Hora_Movimiento CHAR(10) DEFAULT NULL,
  Fecha_Movimeinto CHAR(20) DEFAULT NULL,
  Medida CHAR(20) DEFAULT NULL,
  No_Contenedor CHAR(20) DEFAULT NULL,
  Ingreso_Movimiento CHAR(10) DEFAULT NULL,
  Cliente CHAR(20) DEFAULT NULL,
  Actividad CHAR(20) DEFAULT NULL,
  Motivo CHAR(20) DEFAULT NULL,
  Despacho_Movimeinto CHAR(20) DEFAULT NULL,
  Importacion CHAR(20) DEFAULT NULL,
  Exportacion CHAR(20) DEFAULT NULL,
  Adicionales CHAR(20) DEFAULT NULL,
  Movimiento_Interno CHAR(20) DEFAULT NULL,
  Observaciones VARCHAR(75) DEFAULT NULL,
  Fecha_Movimiento DATE DEFAULT NULL,
  Horario_Turno CHAR(20) DEFAULT NULL,
  Kalmar_No CHAR(20) DEFAULT NULL,
  id_usuario INT(11) NOT NULL,
  PRIMARY KEY (Id_Movimientos, id_usuario)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE movimientos 
  ADD CONSTRAINT mov_usuario FOREIGN KEY (id_usuario)
    REFERENCES usuarios(id_usuario);

--
-- Create table `flota_transporte`
--
CREATE TABLE flota_transporte (
  Id_f INT(11) NOT NULL AUTO_INCREMENT,
  Cabezal CHAR(20) DEFAULT NULL,
  Nombre_de_Piloto CHAR(20) DEFAULT NULL,
  Licencias CHAR(20) DEFAULT NULL,
  Placas CHAR(20) DEFAULT NULL,
  Codigo_Piloto_Naviera CHAR(20) DEFAULT NULL,
  Naviera CHAR(20) DEFAULT NULL,
  Creadopor CHAR(20) DEFAULT NULL,
  Estado INT(11) DEFAULT NULL,
  Fechacreacion DATE DEFAULT NULL,
  Transporte VARCHAR(20) DEFAULT NULL,
  Ubicacion CHAR(20) DEFAULT NULL,
  PRIMARY KEY (Id_f)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `vacios_despachos`
--
CREATE TABLE vacios_despachos (
  Id_vd INT(11) NOT NULL AUTO_INCREMENT,
  Fecha_Despacho CHAR(20) DEFAULT NULL,
  Hora_De_Despacho CHAR(20) DEFAULT NULL,
  Marchamo CHAR(20) DEFAULT NULL,
  Digitador CHAR(20) DEFAULT NULL,
  Id_f INT(11) NOT NULL,
  Id INT(11) NOT NULL,
  id_usuario INT(11) NOT NULL,
  PRIMARY KEY (Id_vd)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE vacios_despachos 
  ADD CONSTRAINT flota_vacio_d FOREIGN KEY (Id_f)
    REFERENCES flota_transporte(Id_f);

--
-- Create foreign key
--
ALTER TABLE vacios_despachos 
  ADD CONSTRAINT vacios_ingreso_despacho_v FOREIGN KEY (Id, id_usuario)
    REFERENCES vacios_ingresos(Id, id_usuario);

--
-- Create table `ingreso_maestro`
--
CREATE TABLE ingreso_maestro (
  Id_Ingreso INT(11) NOT NULL AUTO_INCREMENT,
  Fecha_ingreso DATE DEFAULT NULL,
  Hora_ingreso CHAR(20) DEFAULT NULL,
  No_Contenedor CHAR(20) DEFAULT NULL,
  Barco VARCHAR(50) DEFAULT NULL,
  Tipo_Contenido CHAR(20) DEFAULT NULL,
  Descripcion_contenido VARCHAR(50) DEFAULT NULL,
  Detalle_Servicio VARCHAR(20) DEFAULT NULL,
  Marchamo CHAR(20) DEFAULT NULL,
  Hora_TIR CHAR(10) DEFAULT NULL,
  Serie_TIR CHAR(5) DEFAULT NULL,
  producto VARCHAR(30) DEFAULT NULL,
  Ord INT(11) DEFAULT NULL,
  Bloque CHAR(20) DEFAULT NULL,
  Posicion INT(11) DEFAULT NULL,
  Observaciones CHAR(20) DEFAULT NULL,
  Destino CHAR(20) DEFAULT NULL,
  Fecha_Asignacion DATE DEFAULT NULL,
  Estado CHAR(20) DEFAULT NULL,
  Id_f INT(11) NOT NULL,
  id_usuario INT(11) NOT NULL,
  PRIMARY KEY (Id_Ingreso, Id_f, id_usuario),
  UNIQUE INDEX UK_ingreso_maestro(Id_Ingreso, id_usuario)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE ingreso_maestro 
  ADD CONSTRAINT flota_ingreso_m FOREIGN KEY (Id_f)
    REFERENCES flota_transporte(Id_f);

--
-- Create foreign key
--
ALTER TABLE ingreso_maestro 
  ADD CONSTRAINT usuario_maestro FOREIGN KEY (id_usuario)
    REFERENCES usuarios(id_usuario);

--
-- Create table `monitoreo`
--
CREATE TABLE monitoreo (
  Id_m INT(11) NOT NULL AUTO_INCREMENT,
  Hora_De_Monitoreo DATETIME DEFAULT NULL,
  Retorno CHAR(20) DEFAULT NULL,
  Observaciones VARCHAR(50) DEFAULT NULL,
  Producto CHAR(20) DEFAULT NULL,
  Set_Point CHAR(20) DEFAULT NULL,
  Suministro VARCHAR(20) DEFAULT NULL,
  Fecha_Del_Monitoreo CHAR(20) DEFAULT NULL,
  Nombre_Del_Mecanico CHAR(20) DEFAULT NULL,
  id_ingreso INT(11) NOT NULL,
  Id_f INT(11) NOT NULL,
  id_usuario INT(11) NOT NULL,
  PRIMARY KEY (Id_m, id_ingreso, Id_f, id_usuario)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE monitoreo 
  ADD CONSTRAINT ingreso_m_monitoreo FOREIGN KEY (id_ingreso, id_usuario)
    REFERENCES ingreso_maestro(Id_Ingreso, id_usuario);

DELIMITER $$

--
-- Create procedure `listar_Monitoreo`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE listar_Monitoreo()
BEGIN
SELECT
  a.Id_m,
  b.No_Contenedor,
  a.Hora_De_Monitoreo,
  a.Producto,
  a.Set_Point,
  a.Retorno,
  b.Bloque,
  b.Posicion,
  b.Barco,
  a.Fecha_Del_Monitoreo
FROM monitoreo a
  INNER JOIN ingreso_maestro b
    ON a.Id_m = b.Id_Ingreso
  INNER JOIN flota_transporte c
    ON a.Id_f = c.Id_f;
END
$$

--
-- Create procedure `insertar_monitoreo`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE insertar_monitoreo(in horamonitoreo char(10),
  in retorno varchar(30),in observaciones varchar(70),in producto char(20),
  in setpoint char(20),in suministro varchar(20),fechaminitoreo char(10),
  in mecanico char(20),in idingreso int,in idf int,in idusuarios int)
BEGIN
Start transaction;
INSERT INTO monitoreo (Hora_De_Monitoreo, Retorno, Observaciones, Producto,
Set_Point, Suministro, Fecha_Del_Monitoreo, Nombre_Del_Mecanico,
Nombre_Del_Mecanico, id_ingreso, Id_f, id_usuario)
  VALUES (horamonitoreo, retorno, observaciones, producto, setpoint, suministro, fechaminitoreo, mecanico, idingreso, idf, idusuarios);
if (@@error_count=0) then
  commit;
  else
  rollback;
  end if;
commit;
END
$$

DELIMITER ;

--
-- Create table `exportacion`
--
CREATE TABLE exportacion (
  Id_e INT(11) NOT NULL AUTO_INCREMENT,
  Fecha_de_salida CHAR(20) DEFAULT NULL,
  Hora_de_Salida DATE DEFAULT NULL,
  id INT(11) NOT NULL,
  Id_f INT(11) NOT NULL,
  id_usuario INT(11) NOT NULL,
  PRIMARY KEY (Id_e, id, Id_f, id_usuario)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE exportacion 
  ADD CONSTRAINT ingreso_m_export FOREIGN KEY (id, Id_f, id_usuario)
    REFERENCES ingreso_maestro(Id_Ingreso, Id_f, id_usuario);

--
-- Create table `envios`
--
CREATE TABLE envios (
  Id_en INT(11) NOT NULL AUTO_INCREMENT,
  No_Envio INT(11) DEFAULT NULL,
  Fecha_Envio DATE DEFAULT NULL,
  id INT(11) NOT NULL,
  Id_f INT(11) NOT NULL,
  id_usuario INT(11) NOT NULL,
  PRIMARY KEY (Id_en, id, Id_f, id_usuario)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE envios 
  ADD CONSTRAINT ingreso_m_envio FOREIGN KEY (id, Id_f, id_usuario)
    REFERENCES ingreso_maestro(Id_Ingreso, Id_f, id_usuario);

--
-- Create table `desconexion`
--
CREATE TABLE desconexion (
  Id_d INT(11) NOT NULL AUTO_INCREMENT,
  Fecha_De_Desconexion DATE DEFAULT NULL,
  Hora_De_Desconexio DATETIME DEFAULT NULL,
  totalhoras CHAR(20) DEFAULT NULL,
  observaciones VARCHAR(75) DEFAULT NULL,
  id INT(11) NOT NULL,
  Id_f INT(11) NOT NULL,
  id_usuario INT(11) NOT NULL,
  PRIMARY KEY (Id_d, id, Id_f, id_usuario)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE desconexion 
  ADD CONSTRAINT ingreso_m_desconexion FOREIGN KEY (id, Id_f, id_usuario)
    REFERENCES ingreso_maestro(Id_Ingreso, Id_f, id_usuario);

--
-- Create table `conexion`
--
CREATE TABLE conexion (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Fecha_Conexion DATE DEFAULT NULL,
  Hora_De_Conexion CHAR(10) DEFAULT NULL,
  Setpoint DECIMAL(5, 2) DEFAULT NULL,
  Suministro DECIMAL(5, 2) DEFAULT NULL,
  Retorno DECIMAL(5, 2) DEFAULT NULL,
  Id_ingreso INT(11) NOT NULL,
  Id_f INT(11) NOT NULL,
  Id_usuario INT(11) NOT NULL,
  PRIMARY KEY (Id, Id_ingreso, Id_f, Id_usuario)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE conexion 
  ADD CONSTRAINT ingreso_m_conexion FOREIGN KEY (Id_ingreso, Id_f, Id_usuario)
    REFERENCES ingreso_maestro(Id_Ingreso, Id_f, id_usuario);

--
-- Create table `asignaciones`
--
CREATE TABLE asignaciones (
  Id_a INT(11) NOT NULL AUTO_INCREMENT,
  observaciones CHAR(20) DEFAULT NULL,
  id INT(11) NOT NULL,
  Id_f INT(11) NOT NULL,
  id_usuario INT(11) NOT NULL,
  PRIMARY KEY (Id_a, id, Id_f, id_usuario)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE asignaciones 
  ADD CONSTRAINT ingreso_m_asignaciones FOREIGN KEY (id, Id_f, id_usuario)
    REFERENCES ingreso_maestro(Id_Ingreso, Id_f, id_usuario);

--
-- Create table `bloque`
--
CREATE TABLE bloque (
  id_bloque INT(11) NOT NULL AUTO_INCREMENT,
  Descripcion CHAR(20) DEFAULT NULL,
  PRIMARY KEY (id_bloque)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `posicion`
--
CREATE TABLE posicion (
  idposicion INT(11) NOT NULL AUTO_INCREMENT,
  noposicion INT(11) DEFAULT NULL,
  estado CHAR(20) DEFAULT NULL,
  idbloque INT(11) DEFAULT NULL,
  id_ingreso INT(11) DEFAULT NULL,
  PRIMARY KEY (idposicion)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE posicion 
  ADD CONSTRAINT FK_posicion_idbloque FOREIGN KEY (idbloque)
    REFERENCES bloque(id_bloque) ON DELETE NO ACTION;

DELIMITER $$

--
-- Create procedure `listardatosm`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE listardatosm()
BEGIN
SELECT
  a.Id_Ingreso,
  b.Nombre_de_Piloto,
  b.Placas,
  a.No_Contenedor,
  a.Marchamo,
  c.Descripcion Bloque,
  d.noPosicion Posicion,
  a.producto,
  a.Barco,
  a.Destino,
  a.Estado,
  a.Bloque idb,
  a.Posicion idp,
  a.Id_f
FROM ingreso_maestro a
  INNER JOIN flota_transporte b
    ON a.Id_f = b.Id_f
  INNER JOIN bloque c
    ON a.Bloque = c.id_bloque
  INNER JOIN posicion d
    ON a.Posicion = d.idPosicion
    AND a.Bloque = d.idbloque
WHERE b.Estado = 1
AND a.Estado IN ('Ingresado', 'Anulado');
END
$$

--
-- Create procedure `datosingreso`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE datosingreso(in idingreso int)
BEGIN
SELECT
  a.Ord,
  a.producto,
  b.Descripcion,
  c.noposicion,
  a.Barco,
  a.Id_f
FROM ingreso_maestro a
  INNER JOIN bloque b
    ON a.Bloque = b.id_bloque
  INNER JOIN posicion c
    ON a.Posicion = c.noposicion
    AND a.Bloque = c.idbloque
WHERE a.Id_Ingreso = idingreso
AND a.Estado = 'ingresado';
END
$$

--
-- Create procedure `actualizar_ingreso`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE actualizar_ingreso(IN `idingreso` INT, IN `fechaingreso` DATE, IN `horaingreso` CHAR(20), IN `nocontenedor` CHAR(20), IN `barco` VARCHAR(50), IN `tipocontenido` CHAR(20), IN `dcontenido` VARCHAR(20), IN `dservicio` VARCHAR(50), IN `marchamo` CHAR(20), IN `htir` CHAR(10), IN `serietir` CHAR(5), IN `producto` VARCHAR(30), IN `orden` INT, IN `bloque` CHAR(20), IN `posicion` INT, IN `destino` CHAR(20), IN `fechaasignacion` DATE, IN `observaciones` VARCHAR(200), IN `idf` INT, IN `idusuario` INT)
BEGIN
  DECLARE posiciona int;
  DECLARE bloquea char(20);

SELECT
  Bloque,
  Posicion INTO bloquea, posiciona
FROM ingreso_maestro
WHERE Id_Ingreso = idingreso;
UPDATE posicion
SET id_ingreso = 0,
    estado = 'Sin Asignar'
WHERE id_ingreso = idingreso;

UPDATE ingreso_maestro
SET Fecha_ingreso = fechaingreso,
    Hora_ingreso = horaingreso,
    No_Contenedor = nocontenedor,
    Barco = barco,
    Tipo_Contenido = tipocontenido,
    Descripcion_contenido = dcontenido,
    Detalle_Servicio = dservicio,
    Marchamo = marchamo,
    Hora_TIR = htir,
    Serie_TIR = serietir,
    producto = producto,
    Ord = orden,
    Bloque = bloque,
    Posicion = posicion,
    Observaciones = observaciones,
    Destino = destino,
    Fecha_Asignacion = fechaasignacion,
    Estado = 'Ingresado',
    Id_f = idf,
    id_usuario = idusuario
WHERE Id_Ingreso = idingreso;

UPDATE posicion
SET id_ingreso = idingreso,
    estado = 'Asignado'
WHERE idPosicion = posicion
AND idbloque = bloque;

END
$$

DELIMITER ;

--
-- Create table `permiso`
--
CREATE TABLE permiso (
  idpermiso INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(30) NOT NULL,
  PRIMARY KEY (idpermiso)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `usuario_permiso`
--
CREATE TABLE usuario_permiso (
  idusuario_permiso INT(11) NOT NULL AUTO_INCREMENT,
  idusuario INT(11) NOT NULL,
  idpermiso INT(11) NOT NULL,
  PRIMARY KEY (idusuario_permiso)
)
ENGINE = INNODB,
AUTO_INCREMENT = 14,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `fk_u_permiso_usuario_idx` on table `usuario_permiso`
--
ALTER TABLE usuario_permiso 
  ADD INDEX fk_u_permiso_usuario_idx(idusuario);

--
-- Create index `fk_usuario_permiso_idx` on table `usuario_permiso`
--
ALTER TABLE usuario_permiso 
  ADD INDEX fk_usuario_permiso_idx(idpermiso);

--
-- Create foreign key
--
ALTER TABLE usuario_permiso 
  ADD CONSTRAINT fk_u_permiso_usuario FOREIGN KEY (idusuario)
    REFERENCES usuarios(id_usuario) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE usuario_permiso 
  ADD CONSTRAINT fk_usuario_permiso FOREIGN KEY (idpermiso)
    REFERENCES permiso(idpermiso) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `vacios_flota`
--
CREATE TABLE vacios_flota (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Cabezal CHAR(20) DEFAULT NULL,
  Codigo_Cabezal CHAR(20) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;