--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.505.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 29/04/2021 23:48:06
-- Server version: 10.4.18
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE sis_invcon;

--
-- Drop table `bitacora`
--
DROP TABLE IF EXISTS bitacora;

--
-- Drop table `dfallatir`
--
DROP TABLE IF EXISTS dfallatir;

--
-- Drop table `tamaniochasis`
--
DROP TABLE IF EXISTS tamaniochasis;

--
-- Drop table `vacios_flota`
--
DROP TABLE IF EXISTS vacios_flota;

--
-- Drop procedure `insert_tir`
--
DROP PROCEDURE IF EXISTS insert_tir;

--
-- Drop table `tipocontenedor`
--
DROP TABLE IF EXISTS tipocontenedor;

--
-- Drop table `usuario_permiso`
--
DROP TABLE IF EXISTS usuario_permiso;

--
-- Drop table `permiso`
--
DROP TABLE IF EXISTS permiso;

--
-- Drop procedure `actualizar_asign`
--
DROP PROCEDURE IF EXISTS actualizar_asign;

--
-- Drop procedure `actualizar_asignaciones`
--
DROP PROCEDURE IF EXISTS actualizar_asignaciones;

--
-- Drop procedure `actualizar_ingreso`
--
DROP PROCEDURE IF EXISTS actualizar_ingreso;

--
-- Drop procedure `datosingreso`
--
DROP PROCEDURE IF EXISTS datosingreso;

--
-- Drop procedure `datosingreso_asig`
--
DROP PROCEDURE IF EXISTS datosingreso_asig;

--
-- Drop procedure `datosingreso_c`
--
DROP PROCEDURE IF EXISTS datosingreso_c;

--
-- Drop procedure `insert_fallastir`
--
DROP PROCEDURE IF EXISTS insert_fallastir;

--
-- Drop procedure `insertar_asign`
--
DROP PROCEDURE IF EXISTS insertar_asign;

--
-- Drop procedure `listar_asignaciones`
--
DROP PROCEDURE IF EXISTS listar_asignaciones;

--
-- Drop procedure `listardatosm`
--
DROP PROCEDURE IF EXISTS listardatosm;

--
-- Drop table `posicion`
--
DROP TABLE IF EXISTS posicion;

--
-- Drop procedure `listar_Monitoreo`
--
DROP PROCEDURE IF EXISTS listar_Monitoreo;

--
-- Drop table `bloque`
--
DROP TABLE IF EXISTS bloque;

--
-- Drop procedure `mostrar_asignacion`
--
DROP PROCEDURE IF EXISTS mostrar_asignacion;

--
-- Drop table `asignaciones`
--
DROP TABLE IF EXISTS asignaciones;

--
-- Drop procedure `actualizar_conexion`
--
DROP PROCEDURE IF EXISTS actualizar_conexion;

--
-- Drop procedure `datosconexion`
--
DROP PROCEDURE IF EXISTS datosconexion;

--
-- Drop procedure `insertar_cone`
--
DROP PROCEDURE IF EXISTS insertar_cone;

--
-- Drop procedure `mostrar_conexiones`
--
DROP PROCEDURE IF EXISTS mostrar_conexiones;

--
-- Drop procedure `mostrar_dato_conexion`
--
DROP PROCEDURE IF EXISTS mostrar_dato_conexion;

--
-- Drop procedure `mostrar_desconexion`
--
DROP PROCEDURE IF EXISTS mostrar_desconexion;

--
-- Drop table `conexion`
--
DROP TABLE IF EXISTS conexion;

--
-- Drop table `fallas_tir`
--
DROP TABLE IF EXISTS fallas_tir;

--
-- Drop procedure `mostrar_datostir`
--
DROP PROCEDURE IF EXISTS mostrar_datostir;

--
-- Drop table `datostir`
--
DROP TABLE IF EXISTS datostir;

--
-- Drop procedure `actualizar_desconexion`
--
DROP PROCEDURE IF EXISTS actualizar_desconexion;

--
-- Drop procedure `Insertar_desconexion`
--
DROP PROCEDURE IF EXISTS Insertar_desconexion;

--
-- Drop table `desconexion`
--
DROP TABLE IF EXISTS desconexion;

--
-- Drop table `envios`
--
DROP TABLE IF EXISTS envios;

--
-- Drop table `exportacion`
--
DROP TABLE IF EXISTS exportacion;

--
-- Drop procedure `actualizar_monitoreo`
--
DROP PROCEDURE IF EXISTS actualizar_monitoreo;

--
-- Drop procedure `insertar_monitoreo`
--
DROP PROCEDURE IF EXISTS insertar_monitoreo;

--
-- Drop procedure `mostrar_datos_monitoreo`
--
DROP PROCEDURE IF EXISTS mostrar_datos_monitoreo;

--
-- Drop table `monitoreo`
--
DROP TABLE IF EXISTS monitoreo;

--
-- Drop procedure `datosingreso_datostir`
--
DROP PROCEDURE IF EXISTS datosingreso_datostir;

--
-- Drop table `ingreso_maestro`
--
DROP TABLE IF EXISTS ingreso_maestro;

--
-- Drop table `vacios_despachos`
--
DROP TABLE IF EXISTS vacios_despachos;

--
-- Drop table `flota_transporte`
--
DROP TABLE IF EXISTS flota_transporte;

--
-- Drop table `movimientos`
--
DROP TABLE IF EXISTS movimientos;

--
-- Drop table `vacios_ingresos`
--
DROP TABLE IF EXISTS vacios_ingresos;

--
-- Drop table `usuarios`
--
DROP TABLE IF EXISTS usuarios;

--
-- Drop table `rol`
--
DROP TABLE IF EXISTS rol;

--
-- Set default database
--
USE sis_invcon;

--
-- Create table `rol`
--
CREATE TABLE rol (
  id_rol INT(11) NOT NULL AUTO_INCREMENT,
  descripcion CHAR(20) DEFAULT NULL,
  PRIMARY KEY (id_rol)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `usuarios`
--
CREATE TABLE usuarios (
  id_usuario INT(11) NOT NULL AUTO_INCREMENT,
  nombre_usuario CHAR(20) DEFAULT NULL,
  usuario CHAR(20) DEFAULT NULL,
  clave VARCHAR(250) DEFAULT NULL,
  condicion INT(11) DEFAULT NULL,
  id_rol INT(11) DEFAULT NULL,
  imagen VARCHAR(50) DEFAULT NULL,
  email VARCHAR(75) DEFAULT NULL,
  departamento VARCHAR(50) DEFAULT NULL,
  empresa VARCHAR(75) DEFAULT NULL,
  PRIMARY KEY (id_usuario)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE usuarios 
  ADD CONSTRAINT usuario_rol FOREIGN KEY (id_rol)
    REFERENCES rol(id_rol);

--
-- Create table `vacios_ingresos`
--
CREATE TABLE vacios_ingresos (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Fecha_Ingreso DATE DEFAULT NULL,
  Hora_De_Ingreso DATETIME DEFAULT NULL,
  SZ CHAR(20) DEFAULT NULL,
  Dry_Reefer CHAR(20) DEFAULT NULL,
  Clasificacion CHAR(20) DEFAULT NULL,
  Contenido CHAR(20) DEFAULT NULL,
  Procedencia CHAR(20) DEFAULT NULL,
  TIR CHAR(20) DEFAULT NULL,
  HR_TIR CHAR(20) DEFAULT NULL,
  Transporte CHAR(20) DEFAULT NULL,
  Ubicacion CHAR(20) DEFAULT NULL,
  Estatus CHAR(20) DEFAULT NULL,
  Predio_From CHAR(20) DEFAULT NULL,
  Fecha DATE DEFAULT NULL,
  Sello_Export CHAR(20) DEFAULT NULL,
  Sello_Alopsa CHAR(20) DEFAULT NULL,
  Buque CHAR(20) DEFAULT NULL,
  ETA CHAR(20) DEFAULT NULL,
  Booking CHAR(20) DEFAULT NULL,
  Cliente CHAR(20) DEFAULT NULL,
  Producto CHAR(20) DEFAULT NULL,
  No_De_ATC CHAR(20) DEFAULT NULL,
  Peso_Tara CHAR(20) DEFAULT NULL,
  Fecha_Emision CHAR(20) DEFAULT NULL,
  Fecha_Vencimiento CHAR(20) DEFAULT NULL,
  Fecha_Actual CHAR(20) DEFAULT NULL,
  Dias_Estadia CHAR(20) DEFAULT NULL,
  Problemas_ATC CHAR(20) DEFAULT NULL,
  Forecast CHAR(20) DEFAULT NULL,
  Chatarra CHAR(20) DEFAULT NULL,
  Daños CHAR(20) DEFAULT NULL,
  Año_De_Fabricacion DATE DEFAULT NULL,
  id_usuario INT(11) NOT NULL,
  PRIMARY KEY (Id, id_usuario)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE vacios_ingresos 
  ADD CONSTRAINT usuario_vacio_ingreso FOREIGN KEY (id_usuario)
    REFERENCES usuarios(id_usuario);

--
-- Create table `movimientos`
--
CREATE TABLE movimientos (
  Id_Movimientos INT(11) NOT NULL AUTO_INCREMENT,
  Semana CHAR(20) DEFAULT NULL,
  Año CHAR(20) DEFAULT NULL,
  Hora_Movimiento CHAR(10) DEFAULT NULL,
  Fecha_Movimeinto CHAR(20) DEFAULT NULL,
  Medida CHAR(20) DEFAULT NULL,
  No_Contenedor CHAR(20) DEFAULT NULL,
  Ingreso_Movimiento CHAR(10) DEFAULT NULL,
  Cliente CHAR(20) DEFAULT NULL,
  Actividad CHAR(20) DEFAULT NULL,
  Motivo CHAR(20) DEFAULT NULL,
  Despacho_Movimeinto CHAR(20) DEFAULT NULL,
  Importacion CHAR(20) DEFAULT NULL,
  Exportacion CHAR(20) DEFAULT NULL,
  Adicionales CHAR(20) DEFAULT NULL,
  Movimiento_Interno CHAR(20) DEFAULT NULL,
  Observaciones VARCHAR(75) DEFAULT NULL,
  Fecha_Movimiento DATE DEFAULT NULL,
  Horario_Turno CHAR(20) DEFAULT NULL,
  Kalmar_No CHAR(20) DEFAULT NULL,
  id_usuario INT(11) NOT NULL,
  PRIMARY KEY (Id_Movimientos, id_usuario)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE movimientos 
  ADD CONSTRAINT mov_usuario FOREIGN KEY (id_usuario)
    REFERENCES usuarios(id_usuario);

--
-- Create table `flota_transporte`
--
CREATE TABLE flota_transporte (
  Id_f INT(11) NOT NULL AUTO_INCREMENT,
  Cabezal CHAR(20) DEFAULT NULL,
  Nombre_de_Piloto CHAR(20) DEFAULT NULL,
  Licencias CHAR(20) DEFAULT NULL,
  Placas CHAR(20) DEFAULT NULL,
  Codigo_Piloto_Naviera CHAR(20) DEFAULT NULL,
  Naviera CHAR(20) DEFAULT NULL,
  Creadopor CHAR(20) DEFAULT NULL,
  Estado INT(11) DEFAULT NULL,
  Fechacreacion DATE DEFAULT NULL,
  Transporte VARCHAR(20) DEFAULT NULL,
  Ubicacion CHAR(20) DEFAULT NULL,
  PRIMARY KEY (Id_f)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `vacios_despachos`
--
CREATE TABLE vacios_despachos (
  Id_vd INT(11) NOT NULL AUTO_INCREMENT,
  Fecha_Despacho CHAR(20) DEFAULT NULL,
  Hora_De_Despacho CHAR(20) DEFAULT NULL,
  Marchamo CHAR(20) DEFAULT NULL,
  Digitador CHAR(20) DEFAULT NULL,
  Id_f INT(11) NOT NULL,
  Id INT(11) NOT NULL,
  id_usuario INT(11) NOT NULL,
  PRIMARY KEY (Id_vd)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE vacios_despachos 
  ADD CONSTRAINT flota_vacio_d FOREIGN KEY (Id_f)
    REFERENCES flota_transporte(Id_f);

--
-- Create foreign key
--
ALTER TABLE vacios_despachos 
  ADD CONSTRAINT vacios_ingreso_despacho_v FOREIGN KEY (Id, id_usuario)
    REFERENCES vacios_ingresos(Id, id_usuario);

--
-- Create table `ingreso_maestro`
--
CREATE TABLE ingreso_maestro (
  Id_Ingreso INT(11) NOT NULL AUTO_INCREMENT,
  Fecha_ingreso DATE DEFAULT NULL,
  Hora_ingreso CHAR(20) DEFAULT NULL,
  No_Contenedor CHAR(20) DEFAULT NULL,
  Barco VARCHAR(50) DEFAULT NULL,
  Tipo_Contenido CHAR(20) DEFAULT NULL,
  Descripcion_contenido VARCHAR(50) DEFAULT NULL,
  Detalle_Servicio VARCHAR(20) DEFAULT NULL,
  Marchamo CHAR(20) DEFAULT NULL,
  Hora_TIR CHAR(10) DEFAULT NULL,
  Serie_TIR CHAR(5) DEFAULT NULL,
  producto VARCHAR(30) DEFAULT NULL,
  Ord INT(11) DEFAULT NULL,
  Bloque CHAR(20) DEFAULT NULL,
  Posicion INT(11) DEFAULT NULL,
  Observaciones CHAR(20) DEFAULT NULL,
  Destino CHAR(20) DEFAULT NULL,
  Fecha_Asignacion DATE DEFAULT NULL,
  Estado CHAR(20) DEFAULT NULL,
  Id_f INT(11) NOT NULL,
  id_usuario INT(11) NOT NULL,
  PRIMARY KEY (Id_Ingreso, Id_f, id_usuario),
  UNIQUE INDEX UK_ingreso_maestro(Id_Ingreso, id_usuario)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE ingreso_maestro 
  ADD CONSTRAINT flota_ingreso_m FOREIGN KEY (Id_f)
    REFERENCES flota_transporte(Id_f);

--
-- Create foreign key
--
ALTER TABLE ingreso_maestro 
  ADD CONSTRAINT usuario_maestro FOREIGN KEY (id_usuario)
    REFERENCES usuarios(id_usuario);

DELIMITER $$

--
-- Create procedure `datosingreso_datostir`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE datosingreso_datostir(in idingreso int)
begin
SELECT
  a.Id_Ingreso,
  a.ord,
  b.Nombre_de_Piloto,
  b.Licencias,
  b.Placas,
  b.Codigo_Piloto_Naviera,
  a.No_Contenedor,
  b.Transporte,
  a.Destino,
  a.Id_f
FROM ingreso_maestro a
  INNER JOIN flota_transporte b
    ON b.Id_f = a.Id_f
WHERE a.Estado = 'Ingresado'
AND a.Id_Ingreso = idingreso;
END
$$

DELIMITER ;

--
-- Create table `monitoreo`
--
CREATE TABLE monitoreo (
  Id_m INT(11) NOT NULL AUTO_INCREMENT,
  Hora_De_Monitoreo CHAR(10) DEFAULT NULL,
  Retorno DECIMAL(5, 2) DEFAULT NULL,
  Observaciones VARCHAR(50) DEFAULT NULL,
  Producto CHAR(20) DEFAULT NULL,
  Set_Point DECIMAL(5, 2) DEFAULT NULL,
  Suministro DECIMAL(5, 2) DEFAULT NULL,
  Fecha_Del_Monitoreo CHAR(20) DEFAULT NULL,
  Nombre_Del_Mecanico CHAR(20) DEFAULT NULL,
  id_ingreso INT(11) NOT NULL,
  Id_f INT(11) NOT NULL,
  id_usuario INT(11) NOT NULL,
  estado VARCHAR(10) DEFAULT NULL,
  temperatura CHAR(2) DEFAULT NULL,
  PRIMARY KEY (Id_m, id_ingreso, Id_f, id_usuario)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE monitoreo 
  ADD CONSTRAINT ingreso_m_monitoreo FOREIGN KEY (id_ingreso, id_usuario)
    REFERENCES ingreso_maestro(Id_Ingreso, id_usuario);

DELIMITER $$

--
-- Create procedure `mostrar_datos_monitoreo`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE mostrar_datos_monitoreo(in idmonitoreo int)
BEGIN
SELECT
  *
FROM monitoreo
WHERE Id_m = idmonitoreo;
END
$$

--
-- Create procedure `insertar_monitoreo`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE insertar_monitoreo(in horamonitoreo char(10),
  in retorno varchar(30),in observaciones varchar(70),in producto char(20),
  in setpoint char(20),in suministro varchar(20),fechamonitoreo char(10),
  in mecanico char(20),in idingreso int,in idf int,in idusuarios int,in temperaura char(2))
BEGIN
start transaction;
INSERT INTO monitoreo (Hora_De_Monitoreo, Retorno, Observaciones, Producto,
Set_Point, Suministro, Fecha_Del_Monitoreo,
Nombre_Del_Mecanico, id_ingreso, Id_f, id_usuario, estado, temperatura)
  VALUES (horamonitoreo, retorno, observaciones, producto, setpoint, suministro, fechamonitoreo, mecanico, idingreso, idf, idusuarios, 'Activo', temperaura);
if (@@error_count=0) then
  commit;
  else
  rollback;
  end if;
commit;
END
$$

--
-- Create procedure `actualizar_monitoreo`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE actualizar_monitoreo(in idmonitoreo int,
  in horamonitoreo char(10),in retorno varchar(30),in observaciones varchar(70),
  in producto char(20),in setpoint char(20),in suministro varchar(20),fechamonitoreo char(10),
  in mecanico char(20),in idingreso int,in idf int,in temperatura char(2))
BEGIN
  start transaction;

UPDATE monitoreo
SET Hora_De_Monitoreo = horamonitoreo,
    Retorno = retorno,
    Observaciones = observaciones,
    Producto = producto,
    Set_Point = setpoint,
    Suministro = suministro,
    Fecha_Del_Monitoreo = fechamonitoreo,
    Nombre_Del_Mecanico = mecanico,
    id_ingreso = idingreso,
    Id_f = idf,
    temperatura = temperatura
WHERE Id_m = idmonitoreo;

  if (@@error_count=0) then 
    commit;
    else
    rollback;
    end if;
commit;
END
$$

DELIMITER ;

--
-- Create table `exportacion`
--
CREATE TABLE exportacion (
  Id_e INT(11) NOT NULL AUTO_INCREMENT,
  Fecha_de_salida CHAR(20) DEFAULT NULL,
  Hora_de_Salida DATE DEFAULT NULL,
  id INT(11) NOT NULL,
  Id_f INT(11) NOT NULL,
  id_usuario INT(11) NOT NULL,
  PRIMARY KEY (Id_e, id, Id_f, id_usuario)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE exportacion 
  ADD CONSTRAINT ingreso_m_export FOREIGN KEY (id, Id_f, id_usuario)
    REFERENCES ingreso_maestro(Id_Ingreso, Id_f, id_usuario);

--
-- Create table `envios`
--
CREATE TABLE envios (
  Id_en INT(11) NOT NULL AUTO_INCREMENT,
  No_Envio INT(11) DEFAULT NULL,
  Fecha_Envio DATE DEFAULT NULL,
  id INT(11) NOT NULL,
  Id_f INT(11) NOT NULL,
  id_usuario INT(11) NOT NULL,
  PRIMARY KEY (Id_en, id, Id_f, id_usuario)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE envios 
  ADD CONSTRAINT ingreso_m_envio FOREIGN KEY (id, Id_f, id_usuario)
    REFERENCES ingreso_maestro(Id_Ingreso, Id_f, id_usuario);

--
-- Create table `desconexion`
--
CREATE TABLE desconexion (
  Id_d INT(11) NOT NULL AUTO_INCREMENT,
  Fecha_De_Desconexion DATE DEFAULT NULL,
  Hora_De_Desconexio CHAR(10) DEFAULT NULL,
  totalhoras CHAR(20) DEFAULT NULL,
  observaciones VARCHAR(75) DEFAULT NULL,
  id INT(11) NOT NULL,
  Id_f INT(11) NOT NULL,
  id_usuario INT(11) NOT NULL,
  estado CHAR(10) DEFAULT NULL,
  idconexion INT(11) DEFAULT NULL,
  PRIMARY KEY (Id_d, id, Id_f, id_usuario)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE desconexion 
  ADD CONSTRAINT ingreso_m_desconexion FOREIGN KEY (id, Id_f, id_usuario)
    REFERENCES ingreso_maestro(Id_Ingreso, Id_f, id_usuario);

DELIMITER $$

--
-- Create procedure `Insertar_desconexion`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE Insertar_desconexion(in fechadesco char(10),
  in horadesco char(10), in totalhoras char(10), in observaciones varchar(70),
  in idf int,in idingre int,in idusuario int,in idconexion int)
BEGIN
  	start transaction;
INSERT INTO desconexion (Fecha_De_Desconexion, Hora_De_Desconexio, totalhoras, observaciones, id, Id_f, id_usuario, estado, idconexion)
  VALUES (fechadesco, horadesco, totalhoras, observaciones, idingre, idf, idusuario, 'Activo', idconexion);
  if (@@error_count=0) then
	commit;
	else
	rollback;
end if;
commit;
END
$$

--
-- Create procedure `actualizar_desconexion`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE actualizar_desconexion(in iddesco int,in fechadesco char(10),
  in horadesco char(10), in totalhoras char(10), in observaciones varchar(70),
  in idf int,in idingre int,in idconexion int)
BEGIN
  start transaction;
UPDATE desconexion
SET Fecha_De_Desconexion = fechadesco,
    Hora_De_Desconexio = horadesco,
    totalhoras = totalhoras,
    observaciones = observaciones,
    id = idingre,
    Id_f = idf,
    idconexion = idconexion
WHERE Id_d = iddesco;

  if (@@error_count=0) then
	commit;
	else
	rollback;
end if;
commit;

END
$$

DELIMITER ;

--
-- Create table `datostir`
--
CREATE TABLE datostir (
  idtir INT(11) NOT NULL AUTO_INCREMENT,
  SerieTir CHAR(2) DEFAULT NULL,
  chassis VARCHAR(10) DEFAULT NULL,
  tipochassis VARCHAR(5) DEFAULT NULL,
  refrigeracion VARCHAR(10) DEFAULT NULL,
  tipocontenedor VARCHAR(10) DEFAULT NULL,
  fecha VARCHAR(10) DEFAULT NULL,
  hora VARCHAR(10) DEFAULT NULL,
  tipomov VARCHAR(10) DEFAULT NULL,
  Nombre_naviera VARCHAR(30) NOT NULL,
  vacio VARCHAR(10) DEFAULT NULL,
  Destino VARCHAR(30) DEFAULT NULL,
  fallaizq BIT(1) DEFAULT NULL,
  fallader BIT(1) DEFAULT NULL,
  fallafre BIT(1) DEFAULT NULL,
  fallainte BIT(1) DEFAULT NULL,
  fallatra BIT(1) DEFAULT NULL,
  fallatec BIT(1) DEFAULT NULL,
  fallachas BIT(1) DEFAULT NULL,
  cliente VARCHAR(100) DEFAULT NULL,
  observaciones VARCHAR(200) DEFAULT NULL,
  idingreso INT(11) DEFAULT NULL,
  id_f INT(11) DEFAULT NULL,
  id_usuario INT(11) DEFAULT NULL,
  estado VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (idtir),
  INDEX datortir_idtir_IDX(idtir)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE datostir 
  ADD CONSTRAINT datortir_FK FOREIGN KEY (idingreso, id_f, id_usuario)
    REFERENCES ingreso_maestro(Id_Ingreso, Id_f, id_usuario);

DELIMITER $$

--
-- Create procedure `mostrar_datostir`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE mostrar_datostir()
begin
SELECT
  im.No_Contenedor,
  a.chassis,
  SerieTir,
  a.fecha,
  a.hora,
  ft.Transporte,
  ft.Nombre_de_Piloto,
  ft.Placas,
  a.Destino,
  a.vacio,
  a.cliente,
  a.idtir
FROM sis_invcon.datostir a
  INNER JOIN ingreso_maestro im
    ON a.idingreso = im.Id_Ingreso
  INNER JOIN flota_transporte ft
    ON a.id_f = ft.Id_f
WHERE a.estado = 'Activo';
END
$$

DELIMITER ;

--
-- Create table `fallas_tir`
--
CREATE TABLE fallas_tir (
  idfalla_tir INT(11) NOT NULL AUTO_INCREMENT,
  id_datostir INT(11) DEFAULT NULL,
  ubicacion CHAR(20) DEFAULT NULL,
  falla VARCHAR(20) DEFAULT NULL,
  opcionfalla BIT(1) DEFAULT NULL,
  Posicion VARCHAR(10) DEFAULT NULL,
  observacion VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (idfalla_tir)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE fallas_tir 
  ADD CONSTRAINT Fallas_TIR_FK FOREIGN KEY (id_datostir)
    REFERENCES datostir(idtir);

--
-- Create table `conexion`
--
CREATE TABLE conexion (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Fecha_Conexion DATE DEFAULT NULL,
  Hora_De_Conexion CHAR(10) DEFAULT NULL,
  Setpoint DECIMAL(5, 2) DEFAULT NULL,
  Suministro DECIMAL(5, 2) DEFAULT NULL,
  Retorno DECIMAL(5, 2) DEFAULT NULL,
  Id_ingreso INT(11) NOT NULL,
  Id_f INT(11) NOT NULL,
  Id_usuario INT(11) NOT NULL,
  Estado CHAR(10) DEFAULT NULL,
  temperatura CHAR(2) DEFAULT NULL,
  tipoconexion VARCHAR(2) DEFAULT NULL,
  PRIMARY KEY (Id, Id_ingreso, Id_f, Id_usuario)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE conexion 
  ADD CONSTRAINT ingreso_m_conexion FOREIGN KEY (Id_ingreso, Id_usuario)
    REFERENCES ingreso_maestro(Id_Ingreso, id_usuario);

DELIMITER $$

--
-- Create procedure `mostrar_desconexion`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE mostrar_desconexion()
BEGIN
SELECT
  a.Fecha_De_Desconexion,
  a.Hora_De_Desconexio,
  a.totalhoras,
  b.Id_Ingreso,
  c.Cabezal,
  c.Nombre_de_Piloto,
  b.No_Contenedor,
  a.Id_d,
  b.Hora_ingreso,
  b.Fecha_ingreso,
  b.Descripcion_contenido,
  d.Id 'idco'
FROM desconexion a
  INNER JOIN ingreso_maestro b
    ON a.id = b.Id_Ingreso
  INNER JOIN flota_transporte c
    ON a.Id_f = c.Id_f
  INNER JOIN conexion d
    ON a.idconexion = d.Id
WHERE a.estado = 'Activo'
AND b.Estado = 'Ingresado';
END
$$

--
-- Create procedure `mostrar_dato_conexion`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE mostrar_dato_conexion(in idconexion int)
BEGIN
SELECT
  *
FROM conexion
WHERE Id = idconexion;
END
$$

--
-- Create procedure `mostrar_conexiones`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE mostrar_conexiones()
BEGIN
SELECT
  a.Id,
  b.No_Contenedor,
  a.Fecha_Conexion,
  a.Hora_De_Conexion,
  a.Setpoint,
  a.Suministro,
  a.Retorno,
  b.Id_Ingreso,
  c.Cabezal,
  c.Nombre_de_Piloto
FROM conexion a
  INNER JOIN ingreso_maestro b
    ON a.Id_ingreso = b.Id_Ingreso
  INNER JOIN flota_transporte c
    ON a.Id_f = c.Id_f
WHERE b.Estado = 'Ingresado'
AND a.Estado = 'Activo';
END
$$

--
-- Create procedure `insertar_cone`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE insertar_cone(in fechac char(10),in horacon char(10),
in setpoint decimal(5,2),in suministro decimal(5,2),in retorno decimal(5,2),
in idingreso int, in idf int,in idusuario int,in temperatura char(2),in tipocon char(2))
BEGIN
	start transaction;
INSERT INTO sis_invcon.conexion (Fecha_Conexion, Hora_De_Conexion, Setpoint, Suministro, Retorno,
Id_ingreso, Id_f, Id_usuario, Estado, temperatura, tipoconexion)
  VALUES (fechac, horacon, setpoint, suministro, retorno, idingreso, idf, idusuario, 'Activo', temperatura, tipocon);
if (@@error_count=0) then
	commit;
	else
	rollback;
end if;
commit;
END
$$

--
-- Create procedure `datosconexion`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE datosconexion(in idconexion int)
BEGIN
SELECT
  a.Fecha_Conexion,
  a.Hora_De_Conexion,
  a.Setpoint,
  a.Suministro,
  b.Fecha_ingreso,
  b.Hora_ingreso,
  c.Cabezal,
  c.Nombre_de_Piloto,
  b.Id_f,
  b.Id_Ingreso
FROM conexion a
  INNER JOIN ingreso_maestro b
    ON a.Id_ingreso = b.Id_Ingreso
  INNER JOIN flota_transporte c
    ON b.Id_f = c.Id_f
WHERE a.id = idconexion;
END
$$

--
-- Create procedure `actualizar_conexion`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE actualizar_conexion(in id_conexion int,in fechac char(10),in horacon char(10),
in setpoint decimal(5,2),in suministro decimal(5,2),in retorno decimal(5,2),
in idingreso int, in idf int,in temperatura char(2),in tipocon char(2))
BEGIN
  start transaction;

UPDATE conexion
SET Fecha_Conexion = fechac,
    Hora_De_Conexion = horacon,
    Setpoint = setpoint,
    Retorno = retorno,
    Suministro = suministro,
    Id_ingreso = idingreso,
    Id_f = Id_f,
    temperatura = temperatura,
    tipoconexion = tipocon
WHERE Id = id_conexion;

  if (@@error_count=0) then
	commit;
	else
	rollback;
end if;
commit;

END
$$

DELIMITER ;

--
-- Create table `asignaciones`
--
CREATE TABLE asignaciones (
  Id_a INT(11) NOT NULL AUTO_INCREMENT,
  observaciones VARCHAR(255) DEFAULT NULL,
  bloque INT(11) DEFAULT NULL,
  posicion INT(11) DEFAULT NULL,
  id INT(11) NOT NULL,
  Id_f INT(11) NOT NULL,
  id_usuario INT(11) NOT NULL,
  PRIMARY KEY (Id_a, id, Id_f, id_usuario)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 32768,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE asignaciones 
  ADD CONSTRAINT ingreso_m_asignaciones FOREIGN KEY (id, Id_f, id_usuario)
    REFERENCES ingreso_maestro(Id_Ingreso, Id_f, id_usuario);

DELIMITER $$

--
-- Create procedure `mostrar_asignacion`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE mostrar_asignacion(in idasignacion int)
begin

SELECT
  *
FROM sis_invcon.asignaciones
WHERE Id_a = idasignacion;
END
$$

DELIMITER ;

--
-- Create table `bloque`
--
CREATE TABLE bloque (
  id_bloque INT(11) NOT NULL AUTO_INCREMENT,
  Descripcion CHAR(20) DEFAULT NULL,
  PRIMARY KEY (id_bloque)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

DELIMITER $$

--
-- Create procedure `listar_Monitoreo`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE listar_Monitoreo()
BEGIN
SELECT
  a.Id_m,
  b.No_Contenedor,
  a.Hora_De_Monitoreo,
  a.Producto,
  a.Set_Point,
  a.Retorno,
  d.Descripcion Bloque,
  b.Posicion,
  b.Barco,
  a.Fecha_Del_Monitoreo
FROM monitoreo a
  INNER JOIN ingreso_maestro b
    ON a.Id_m = b.Id_Ingreso
  INNER JOIN flota_transporte c
    ON a.Id_f = c.Id_f
  INNER JOIN bloque d
    ON b.Bloque = d.id_bloque
WHERE a.estado = 'Activo';
END
$$

DELIMITER ;

--
-- Create table `posicion`
--
CREATE TABLE posicion (
  idposicion INT(11) NOT NULL AUTO_INCREMENT,
  noposicion INT(11) DEFAULT NULL,
  estado CHAR(20) DEFAULT NULL,
  idbloque INT(11) DEFAULT NULL,
  id_ingreso INT(11) DEFAULT NULL,
  PRIMARY KEY (idposicion)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE posicion 
  ADD CONSTRAINT FK_posicion_idbloque FOREIGN KEY (idbloque)
    REFERENCES bloque(id_bloque) ON DELETE NO ACTION;

DELIMITER $$

--
-- Create procedure `listardatosm`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE listardatosm()
BEGIN
SELECT
  a.Id_Ingreso,
  b.Nombre_de_Piloto,
  b.Placas,
  a.No_Contenedor,
  a.Marchamo,
  c.Descripcion Bloque,
  d.noPosicion Posicion,
  a.producto,
  a.Barco,
  a.Destino,
  a.Estado,
  a.Bloque idb,
  a.Posicion idp,
  a.Id_f
FROM ingreso_maestro a
  INNER JOIN flota_transporte b
    ON a.Id_f = b.Id_f
  INNER JOIN bloque c
    ON a.Bloque = c.id_bloque
  INNER JOIN posicion d
    ON a.Posicion = d.idPosicion
    AND a.Bloque = d.idbloque
WHERE b.Estado = 1
AND a.Estado IN ('Ingresado', 'Anulado');
END
$$

--
-- Create procedure `listar_asignaciones`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE listar_asignaciones()
BEGIN
SELECT
  b.Ord,
  a.Id_a,
  c.Nombre_de_Piloto,
  c.Placas,
  c.Codigo_Piloto_Naviera,
  b.No_Contenedor,
  d.Descripcion Bloque,
  e.noposicion Posicion,
  b.producto,
  b.Barco
FROM asignaciones a
  INNER JOIN ingreso_maestro b
    ON a.id = b.Id_Ingreso
  INNER JOIN flota_transporte c
    ON a.Id_f = c.Id_f
  INNER JOIN bloque d
    ON a.bloque = d.id_bloque
  INNER JOIN posicion e
    ON a.posicion = e.idposicion
WHERE b.Estado = 'Ingresado';
END
$$

--
-- Create procedure `insertar_asign`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE insertar_asign(in observaciones varchar(255),
in bloque int,in posicion int,in idingreso int,in idf int,in idusuario int)
BEGIN
start transaction;
INSERT INTO asignaciones (observaciones, bloque, posicion, id, Id_f, id_usuario)
  VALUES (observaciones, bloque, posicion, idingreso, idf, idusuario);

UPDATE posicion
SET id_ingreso = idingreso,
    estado = 'Asignado'
WHERE idPosicion = posicion
AND idbloque = bloque;

if (@@error_count=0) then
	commit;
	else
	rollback;
end if;
commit;

END
$$

--
-- Create procedure `insert_fallastir`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE insert_fallastir(in iddtir int,in ubicacion char(50),in f char(20),in op bit,in obser varchar(50),in pos varchar(10) )
begin
	start transaction;

INSERT INTO sis_invcon.fallas_tir (id_datostir, ubicacion, falla, opcionfalla, observacion, Posicion)
  VALUES (iddtir, ubicacion, f, op, obser, pos);

if (@@error_count=0) then
	commit;
	else
	rollback;
end if;
commit;
END
$$

--
-- Create procedure `datosingreso_c`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE datosingreso_c(in idingreso int)
BEGIN
SELECT
  a.Ord,
  a.producto,
  b.Descripcion,
  c.noposicion,
  a.Barco,
  a.Id_f
FROM ingreso_maestro a
  INNER JOIN bloque b
    ON a.Bloque = b.id_bloque
  INNER JOIN posicion c
    ON a.Posicion = c.idposicion
    AND a.Bloque = c.idbloque
WHERE a.Id_Ingreso = idingreso
AND a.Estado = 'ingresado';
END
$$

--
-- Create procedure `datosingreso_asig`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE datosingreso_asig(in idingreso int)
BEGIN
SELECT
  a.Id_Ingreso,
  a.ord,
  b.Nombre_de_Piloto,
  b.Licencias,
  b.Placas,
  b.Codigo_Piloto_Naviera,
  a.No_Contenedor,
  a.Bloque,
  a.Posicion,
  a.producto,
  a.Barco,
  c.Descripcion,
  d.noposicion,
  a.Id_f
FROM ingreso_maestro a
  INNER JOIN flota_transporte b
    ON b.Id_f = a.Id_f
  INNER JOIN bloque c
    ON a.Bloque = c.id_bloque
  INNER JOIN posicion d
    ON a.Posicion = d.idposicion
WHERE a.Estado = 'Ingresado'
AND a.Id_Ingreso = idingreso;
END
$$

--
-- Create procedure `datosingreso`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE datosingreso(in idingreso int)
BEGIN
SELECT
  a.Ord,
  a.producto,
  b.Descripcion,
  c.noposicion,
  a.Barco,
  a.Id_f
FROM ingreso_maestro a
  INNER JOIN bloque b
    ON a.Bloque = b.id_bloque
  INNER JOIN posicion c
    ON a.Posicion = c.idposicion
    AND a.Bloque = c.idbloque
  INNER JOIN conexion d
    ON d.Id_ingreso = a.Id_Ingreso
WHERE d.Id = idingreso
AND a.Estado = 'ingresado';
END
$$

--
-- Create procedure `actualizar_ingreso`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE actualizar_ingreso(IN `idingreso` INT, IN `fechaingreso` DATE, IN `horaingreso` CHAR(20), IN `nocontenedor` CHAR(20), IN `barco` VARCHAR(50), IN `tipocontenido` CHAR(20), IN `dcontenido` VARCHAR(20), IN `dservicio` VARCHAR(50), IN `marchamo` CHAR(20), IN `htir` CHAR(10), IN `serietir` CHAR(5), IN `producto` VARCHAR(30), IN `orden` INT, IN `bloque` CHAR(20), IN `posicion` INT, IN `destino` CHAR(20), IN `fechaasignacion` DATE, IN `observaciones` VARCHAR(200), IN `idf` INT, IN `idusuario` INT)
BEGIN
  DECLARE posiciona int;
  DECLARE bloquea char(20);

SELECT
  Bloque,
  Posicion INTO bloquea, posiciona
FROM ingreso_maestro
WHERE Id_Ingreso = idingreso;
UPDATE posicion
SET id_ingreso = 0,
    estado = 'Sin Asignar'
WHERE id_ingreso = idingreso;

UPDATE ingreso_maestro
SET Fecha_ingreso = fechaingreso,
    Hora_ingreso = horaingreso,
    No_Contenedor = nocontenedor,
    Barco = barco,
    Tipo_Contenido = tipocontenido,
    Descripcion_contenido = dcontenido,
    Detalle_Servicio = dservicio,
    Marchamo = marchamo,
    Hora_TIR = htir,
    Serie_TIR = serietir,
    producto = producto,
    Ord = orden,
    Bloque = bloque,
    Posicion = posicion,
    Observaciones = observaciones,
    Destino = destino,
    Fecha_Asignacion = fechaasignacion,
    Estado = 'Ingresado',
    Id_f = idf,
    id_usuario = idusuario
WHERE Id_Ingreso = idingreso;

UPDATE posicion
SET id_ingreso = idingreso,
    estado = 'Asignado'
WHERE idPosicion = posicion
AND idbloque = bloque;

END
$$

--
-- Create procedure `actualizar_asignaciones`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE actualizar_asignaciones(in idasignacion int,in Observaciones varchar(255),in Bloque int,
in posiciona int,in idingresoa int,in idfa int)
begin
	 start transaction;
UPDATE sis_invcon.asignaciones
SET observaciones = Observaciones,
    bloque = Bloque,
    posicion = posiciona,
    id = idingresoa,
    Id_f = idfa
WHERE Id_a = idasignacion;

if (@@error_count=0) then
	commit;
	else
	rollback;
end if;
commit;

END
$$

--
-- Create procedure `actualizar_asign`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE actualizar_asign(in idasignacion int, in observaciones varchar(255), in bloque int,in posicion int,
in idingreso int,in idf int)
begin
	start transaction;

UPDATE sis_invcon.asignaciones
SET observaciones = observaciones,
    bloque = bloque,
    posicion = posicion,
    id = idingreso,
    Id_f = idf
WHERE Id_a = idasignacion;

UPDATE sis_invcon.posicion
SET id_ingreso = idingreso,
    estado = 'Asignado'
WHERE idPosicion = posicion
AND idbloque = bloque;
		
if (@@error_count=0) then
	commit;
	else
	rollback;
end if;
commit;
END
$$

DELIMITER ;

--
-- Create table `permiso`
--
CREATE TABLE permiso (
  idpermiso INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(30) NOT NULL,
  PRIMARY KEY (idpermiso)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `usuario_permiso`
--
CREATE TABLE usuario_permiso (
  idusuario_permiso INT(11) NOT NULL AUTO_INCREMENT,
  idusuario INT(11) NOT NULL,
  idpermiso INT(11) NOT NULL,
  PRIMARY KEY (idusuario_permiso)
)
ENGINE = INNODB,
AUTO_INCREMENT = 23,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `fk_u_permiso_usuario_idx` on table `usuario_permiso`
--
ALTER TABLE usuario_permiso 
  ADD INDEX fk_u_permiso_usuario_idx(idusuario);

--
-- Create index `fk_usuario_permiso_idx` on table `usuario_permiso`
--
ALTER TABLE usuario_permiso 
  ADD INDEX fk_usuario_permiso_idx(idpermiso);

--
-- Create foreign key
--
ALTER TABLE usuario_permiso 
  ADD CONSTRAINT fk_u_permiso_usuario FOREIGN KEY (idusuario)
    REFERENCES usuarios(id_usuario) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE usuario_permiso 
  ADD CONSTRAINT fk_usuario_permiso FOREIGN KEY (idpermiso)
    REFERENCES permiso(idpermiso) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `tipocontenedor`
--
CREATE TABLE tipocontenedor (
  id INT(11) NOT NULL AUTO_INCREMENT,
  descripcion VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

DELIMITER $$

--
-- Create procedure `insert_tir`
--
CREATE 
DEFINER = 'root'@'localhost'
PROCEDURE insert_tir(in seriet char(2),in chasis char(10),
in tchasis varchar (5),in refrig varchar(10),in tconten varchar(10),in fechat char(10),
in horat char(10),in tmov char(10),in naviera varchar(30),in vacio varchar(10),in destino varchar(30),
in fizq bit,in fder bit,in ffre bit, in finte bit,in ftra bit,in ftec bit, in fcha bit,
in cli varchar(100), in obser varchar(200), in id_ingre int, in idf int,in idusuario int)
begin
	start transaction;

INSERT INTO sis_invcon.datostir (SerieTir, chassis, tipochassis, refrigeracion, tipocontenedor, fecha, hora,
tipomov, Nombre_naviera, vacio, Destino, fallaizq, fallader, fallafre, fallainte,
fallatra, fallatec, fallachas, cliente, observaciones, idingreso, id_f, id_usuario, estado)
  VALUES (seriet, chasis, tchasis, refrig, tconten, fechat, horat, tmov, naviera, vacio, destino, fizq, fder, ffre, finte, ftra, ftec, fcha, cli, obser, id_ingre, idf, idusuario, 'Activo');
	
 if (@@error_count=0) then
	commit;
SELECT
  LAST_INSERT_ID();
ELSE
	rollback;
end if;
commit;
END
$$

DELIMITER ;

--
-- Create table `vacios_flota`
--
CREATE TABLE vacios_flota (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Cabezal CHAR(20) DEFAULT NULL,
  Codigo_Cabezal CHAR(20) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `tamaniochasis`
--
CREATE TABLE tamaniochasis (
  id INT(11) NOT NULL AUTO_INCREMENT,
  descripcion VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `dfallatir`
--
CREATE TABLE dfallatir (
  id INT(11) NOT NULL AUTO_INCREMENT,
  utfalla VARCHAR(10) DEFAULT NULL,
  falla VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 15,
AVG_ROW_LENGTH = 1489,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `bitacora`
--
CREATE TABLE bitacora (
  id INT(11) NOT NULL AUTO_INCREMENT,
  accion VARCHAR(20) DEFAULT NULL,
  fecha VARCHAR(10) DEFAULT NULL,
  hora VARCHAR(10) DEFAULT NULL,
  usuario VARCHAR(20) DEFAULT NULL,
  descripcion VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX bitacora_id_IDX(id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;